let model,live,teams={},marketHistory={},filter='all';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const fmt=(n,d=2)=>n==null||Number.isNaN(+n)?'—':(+n).toFixed(d);
const KICKOFF={'2026_01_NE_SEA':'2026-09-10T00:20:00Z','2026_01_SF_LA':'2026-09-11T00:35:00Z','2026_01_CHI_CAR':'2026-09-13T17:00:00Z','2026_01_BAL_IND':'2026-09-13T17:00:00Z','2026_01_ATL_PIT':'2026-09-13T17:00:00Z','2026_01_CLE_JAX':'2026-09-13T17:00:00Z','2026_01_TB_CIN':'2026-09-13T17:00:00Z','2026_01_NYJ_TEN':'2026-09-13T17:00:00Z','2026_01_NO_DET':'2026-09-13T17:00:00Z','2026_01_BUF_HOU':'2026-09-13T17:00:00Z','2026_01_ARI_LAC':'2026-09-13T20:25:00Z','2026_01_GB_MIN':'2026-09-13T20:25:00Z','2026_01_MIA_LV':'2026-09-13T20:25:00Z','2026_01_WAS_PHI':'2026-09-13T20:25:00Z','2026_01_DAL_NYG':'2026-09-14T00:20:00Z','2026_01_DEN_KC':'2026-09-15T00:15:00Z'};
function score(id){return (live.scores||[]).find(x=>x.game_id===id)}
function kickoff(g){return score(g.game_id)?.commence_utc||live.game_meta?.[g.game_id]?.commence_utc||KICKOFF[g.game_id]||null}
function kickoffText(g){const s=score(g.game_id);if(s?.state==='FINAL')return 'Final';if(s?.state==='LIVE')return s.detail||'Live';const k=kickoff(g);return k?new Date(k).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}):'Scheduled'}
function teamName(code){return teams[code]?.name||code}
function statusBadge(g){const s=score(g.game_id);if(s?.state==='FINAL')return '<span class="badge lock">FINAL</span>';if(s?.state==='LIVE')return '<span class="badge live">LIVE</span>';if(g.locked)return '<span class="badge lock">LOCKED LIVE</span>';if(g.status==='AUDIT_ONLY_POST_KICKOFF')return '<span class="badge">AUDIT ONLY</span>';return '<span class="badge">CURRENT AS-OF</span>'}
function historyFor(g){return marketHistory[g.game_id]||[]}
function currentMarket(g){const h=historyFor(g);return h.length?h[h.length-1].display:(g.market||'—')}
function currentBooks(g){const h=historyFor(g);return h.length?h[h.length-1].books:null}
function card(g){const s=score(g.game_id),hot=(g.edge||0)>=4;return `<article class="game-card ${g.locked?'locked':''} ${hot?'signal-card':''}" data-game="${g.game_id}"><div class="game-top"><span class="kick">${kickoffText(g)}</span>${statusBadge(g)}</div><div class="matchup-row"><span class="team"><span class="team-bubble">${g.away}</span>${g.away}</span><span class="at">@</span><span class="team"><span class="team-bubble">${g.home}</span>${g.home}</span></div>${s?.state==='FINAL'||s?.state==='LIVE'?`<div class="result-line"><b>${s.away} ${s.away_score}</b><b>${s.home} ${s.home_score}</b></div>`:''}<div class="line-row"><div class="line-box"><small>Our line</small><b>${g.our_line||'—'}</b></div><div class="line-box"><small>Market</small><b>${currentMarket(g)}</b></div><div class="line-box"><small>Edge</small><b class="edge-num ${hot?'hot':''}">${fmt(g.edge)}</b></div></div><div class="line-row"><div class="line-box"><small>Model side</small><b>${g.model_side||'—'}</b></div><div>${g.signal_4plus?'<span class="badge signal">4+ DISCREPANCY</span>':''}</div></div></article>`}
function visibleGames(){let a=[...model.games];if(filter==='locked')a=a.filter(x=>x.locked);if(filter==='signal')a=a.filter(x=>x.signal_4plus);return a}
function bindCards(){$$('.game-card').forEach(x=>x.onclick=()=>openDrawer(x.dataset.game))}
function renderGames(){$('#gameCards').innerHTML=visibleGames().map(card).join('');bindCards()}
function renderHome(){let featured=[...model.games].filter(g=>g.locked||g.signal_4plus);if(featured.length<4)featured=[...featured,...model.games.filter(g=>!featured.includes(g)).slice(0,4-featured.length)];$('#featuredGames').innerHTML=featured.slice(0,4).map(card).join('');bindCards();const outs=(live.injuries||[]).filter(x=>x.game_status==='Out').length,qs=(live.injuries||[]).filter(x=>x.game_status==='Questionable').length;$('#injuryWatch').innerHTML=`<div class="watch-row"><span>Players OUT</span><b>${outs}</b></div><div class="watch-row"><span>Questionable</span><b>${qs}</b></div><div class="watch-row"><span>Official rows shown</span><b>${(live.injuries||[]).length}</b></div>`;const locked=model.games.filter(g=>g.locked).length;$('#ledgerHeadline').textContent=`${locked} locked live game${locked===1?'':'s'}`;const biggest=[...model.games].filter(g=>g.edge!=null).sort((a,b)=>b.edge-a.edge)[0];$('#biggestEdge').innerHTML=biggest?`<h3>${biggest.away} @ ${biggest.home}</h3><div class="watch-row"><span>Difference</span><b class="hot">${fmt(biggest.edge)} pts</b></div><div class="watch-row"><span>Model side</span><b>${biggest.model_side}</b></div><div class="watch-row"><span>Status</span><b>${biggest.locked?'LOCKED':'CURRENT'}</b></div>`:'<p>No market comparison yet.</p>'}
function renderMarket(){const games=[...model.games].filter(g=>g.market||historyFor(g).length);const avg=games.length?games.reduce((s,g)=>s+(g.edge||0),0)/games.length:0;const four=games.filter(g=>(g.edge||0)>=4).length;const books=games.map(currentBooks).filter(x=>x!=null);const avgBooks=books.length?books.reduce((a,b)=>a+b,0)/books.length:0;$('#marketSummary').innerHTML=[[fmt(avg),'Avg abs difference'],[four,'4+ point gaps'],[fmt(avgBooks,1),'Avg books captured']].map(x=>`<div class="summary-card"><span>${x[1]}</span><b>${x[0]}</b></div>`).join('');$('#marketRows').innerHTML=games.sort((a,b)=>(b.edge||0)-(a.edge||0)).map(g=>`<tr><td><b>${g.away} @ ${g.home}</b><span class="sub">${kickoffText(g)}</span></td><td><b>${g.our_line||'—'}</b></td><td>${currentMarket(g)}</td><td class="${(g.edge||0)>=4?'hot':''}">${fmt(g.edge)} pts</td><td><b>${g.model_side||'—'}</b></td><td>${currentBooks(g)??'—'}</td><td>${g.signal_4plus?'<span class="badge signal">4+ · NOT CERTIFIED</span>':'—'}</td></tr>`).join('')}
function renderInjuries(){const arr=[...(live.injuries||[])].sort((a,b)=>a.team.localeCompare(b.team)||a.player.localeCompare(b.player));$('#injuryRows').innerHTML=arr.map(x=>`<tr><td><b>${x.team}</b></td><td>${x.player}</td><td>${x.position||'—'}</td><td>${x.injury||'—'}</td><td>${x.practice||'—'}</td><td><span class="badge ${x.game_status==='Out'?'out':'q'}">${x.game_status||'—'}</span></td><td>${fmt((x.usage_60d||0)*100,1)}%</td></tr>`).join('');const by={};arr.forEach(x=>{by[x.team]??=[];by[x.team].push(x)});$('#injuryTeamCards').innerHTML=Object.entries(by).sort().map(([t,rows])=>{const out=rows.filter(x=>x.game_status==='Out').length,q=rows.filter(x=>x.game_status==='Questionable').length,burden=rows.filter(x=>x.game_status==='Out').reduce((s,x)=>s+(x.usage_60d||0),0);return `<article class="inj-team"><div class="teamline"><strong>${t}</strong><span>${out} OUT · ${q} Q</span></div><div class="burden">${fmt(burden*100,1)}%</div><span>prior-usage OUT burden</span></article>`}).join('')}
function resultMargin(s){return s?Number(s.home_score)-Number(s.away_score):null}
function modelMarginError(g,s){if(!s||s.state!=='FINAL'||g.our_line_internal==null)return null;return Math.abs(resultMargin(s)-Number(g.our_line_internal))}
function renderResults(){const locked=model.games.filter(g=>g.locked),completed=locked.filter(g=>score(g.game_id)?.state==='FINAL'),signals=locked.filter(g=>g.signal_4plus);const errors=completed.map(g=>modelMarginError(g,score(g.game_id))).filter(x=>x!=null);const mae=errors.length?errors.reduce((a,b)=>a+b,0)/errors.length:null;$('#validationCards').innerHTML=[[locked.length,'Immutable live games'],[completed.length,'Completed locked games'],[signals.length,'Locked 4+ signals'],['NO','Hindsight edits']].map(x=>`<div class="kpi"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('#performanceStrip').innerHTML=[[mae==null?'PENDING':fmt(mae),'Live locked MAE'],[completed.length?completed.length:'0','Scored observations'],['008A','Frozen engine']].map(x=>`<div class="summary-card"><span>${x[1]}</span><b>${x[0]}</b></div>`).join('');$('#resultRows').innerHTML=model.games.map(g=>{const s=score(g.game_id),res=s?.state==='FINAL'?`${s.away} ${s.away_score} · ${s.home} ${s.home_score}`:'—',err=modelMarginError(g,s);return `<tr><td><b>${g.away} @ ${g.home}</b><span class="sub">${g.game_id}</span></td><td>${g.our_line||'—'}</td><td>${g.market||'—'}</td><td class="${(g.edge||0)>=4?'hot':''}">${fmt(g.edge)}</td><td><b>${g.model_side||'—'}</b></td><td>${res}</td><td>${err==null?'—':fmt(err)}</td><td>${g.locked?'<span class="badge lock">LOCKED</span>':g.status==='AUDIT_ONLY_POST_KICKOFF'?'<span class="badge">AUDIT</span>':'<span class="badge">NOT YET LOCKED</span>'}</td></tr>`}).join('')}
function renderStandings(){const rec=live.records||{},divs={};Object.entries(teams).forEach(([code,m])=>{divs[m.division]??=[];divs[m.division].push(code)});$('#standingsGrid').innerHTML=Object.keys(divs).sort().map(div=>`<article class="division-card"><h4>${div}</h4>${divs[div].sort().map(t=>`<div class="division-row"><div class="name"><span class="team-bubble">${t}</span><div><b>${t}</b><span>${teamName(t)}</span></div></div><div class="record">${rec[t]||'0-0'}</div></div>`).join('')}</article>`).join('')}
function marketChart(g){const h=historyFor(g);if(!h.length)return '<p class="muted">No captured market history yet.</p>';const vals=h.map(x=>Math.abs(Number(x.market_internal)||0)),mx=Math.max(1,...vals);return `<div class="market-track"><small>${h.length} captured market snapshot${h.length===1?'':'s'}</small><div class="market-points">${h.map((x,i)=>`<span class="market-point" style="height:${Math.max(10,Math.round((Math.abs(Number(x.market_internal)||0)/mx)*50))}px" data-tip="${x.display} · ${new Date(x.ts).toLocaleString()}"></span>`).join('')}</div></div>`}
function openDrawer(id){const g=model.games.find(x=>x.game_id===id);if(!g)return;const s=score(id),inj=(live.injuries||[]).filter(x=>x.team===g.away||x.team===g.home),hot=(g.edge||0)>=4,meta=live.game_meta?.[id]||{},edgeWidth=Math.min(100,((g.edge||0)/8)*100);$('#drawerBody').innerHTML=`<small>${kickoffText(g)} · ${g.game_id}</small><h2>${teamName(g.away)} @ ${teamName(g.home)}</h2>${statusBadge(g)}<div class="drawer-section"><div class="drawer-metrics"><div class="drawer-metric"><span>Our line</span><b>${g.our_line||'—'}</b></div><div class="drawer-metric"><span>Market</span><b>${currentMarket(g)}</b></div><div class="drawer-metric"><span>Difference</span><b class="${hot?'hot':''}">${fmt(g.edge)}</b></div></div><div class="edge-bar"><span style="width:${edgeWidth}%"></span></div>${marketChart(g)}</div><div class="drawer-section"><h4>Model view</h4><p><b>Model side: ${g.model_side||'—'}</b></p><p>${g.locked?'This prediction is prospectively locked and immutable.':'Current-as-of model view. It is not yet an Experiment 030 live lock.'}</p>${g.signal_4plus?'<span class="badge signal">4+ POINT DISCREPANCY · POST_HOC_NOT_CERTIFIED</span>':''}</div><div class="drawer-section"><h4>Game information</h4><p>${meta.venue||'Venue pending'}${meta.network?`<br>${meta.network}`:''}${kickoff(g)?`<br>${new Date(kickoff(g)).toLocaleString()}`:''}</p>${s?`<p><b>${s.away} ${s.away_score} · ${s.home} ${s.home_score}</b><br>${s.detail||s.state}</p>`:''}</div><div class="drawer-section"><h4>Injury watch</h4>${inj.length?inj.map(x=>`<div class="watch-row"><span>${x.team} · ${x.player} · ${x.position||''}</span><b class="${x.game_status==='Out'?'out':'q'}">${x.game_status}</b></div>`).join(''):'<p>No frozen-status rows currently displayed for these teams.</p>'}</div><div class="drawer-section"><h4>Governance</h4><p>008A Ridge · 002D efficiency + 007C availability<br>Market used as model input: <b>NO</b><br>4+ signal certified: <b>NO</b></p></div>`;$('#gameDrawer').classList.add('open');$('#drawerBackdrop').classList.add('open');$('#gameDrawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#gameDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('open');$('#gameDrawer').setAttribute('aria-hidden','true')}
function gotoTab(id){$$('.navtabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:document.querySelector('.navtabs').offsetTop-80,behavior:'smooth'})}
function render(){const gs=model.games,locked=gs.filter(x=>x.locked).length,pros=gs.filter(x=>x.status!=='AUDIT_ONLY_POST_KICKOFF').length,finals=gs.filter(g=>score(g.game_id)?.state==='FINAL').length,sig=gs.filter(g=>g.signal_4plus).length;$('#updated').textContent='Updated '+new Date(live.updated_at_utc||model.generated_at_utc).toLocaleString();$('#kpis').innerHTML=[[gs.length,'Week 1 games'],[pros,'Prospective games'],[locked,'Immutable live rows'],[sig,'Current 4+ discrepancies']].map(x=>`<div class="kpi"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');renderHome();renderGames();renderMarket();renderInjuries();renderResults();renderStandings()}
$$('.navtabs button').forEach(b=>b.onclick=()=>gotoTab(b.dataset.tab));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderGames()});$$('[data-goto]').forEach(b=>b.onclick=()=>gotoTab(b.dataset.goto));$('#closeDrawer').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
Promise.all([fetch('data/model_snapshot.json?'+Date.now()).then(r=>r.json()),fetch('data/dashboard.json?'+Date.now()).then(r=>r.json()),fetch('data/team_meta.json?'+Date.now()).then(r=>r.json()),fetch('data/market_history.json?'+Date.now()).then(r=>r.json())]).then(([m,l,t,h])=>{model=m;live=l;teams=t;marketHistory=h;render()}).catch(e=>{$('#updated').textContent='Data load error';console.error(e)});
