let model={},live={},teams={},marketHistory={},features={},filter='all',selectedGame=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const fmt=(n,d=2)=>n==null||Number.isNaN(+n)?'—':(+n).toFixed(d);
const KICKOFF={'2026_01_NE_SEA':'2026-09-10T00:20:00Z','2026_01_SF_LA':'2026-09-11T00:35:00Z','2026_01_CHI_CAR':'2026-09-13T17:00:00Z','2026_01_BAL_IND':'2026-09-13T17:00:00Z','2026_01_ATL_PIT':'2026-09-13T17:00:00Z','2026_01_CLE_JAX':'2026-09-13T17:00:00Z','2026_01_TB_CIN':'2026-09-13T17:00:00Z','2026_01_NYJ_TEN':'2026-09-13T17:00:00Z','2026_01_NO_DET':'2026-09-13T17:00:00Z','2026_01_BUF_HOU':'2026-09-13T17:00:00Z','2026_01_ARI_LAC':'2026-09-13T20:25:00Z','2026_01_GB_MIN':'2026-09-13T20:25:00Z','2026_01_MIA_LV':'2026-09-13T20:25:00Z','2026_01_WAS_PHI':'2026-09-13T20:25:00Z','2026_01_DAL_NYG':'2026-09-14T00:20:00Z','2026_01_DEN_KC':'2026-09-15T00:15:00Z'};
const DIVS={ARI:'NFC West',ATL:'NFC South',BAL:'AFC North',BUF:'AFC East',CAR:'NFC South',CHI:'NFC North',CIN:'AFC North',CLE:'AFC North',DAL:'NFC East',DEN:'AFC West',DET:'NFC North',GB:'NFC North',HOU:'AFC South',IND:'AFC South',JAX:'AFC South',KC:'AFC West',LAC:'AFC West',LA:'NFC West',LV:'AFC West',MIA:'AFC East',MIN:'NFC North',NE:'AFC East',NO:'NFC South',NYG:'NFC East',NYJ:'AFC East',PHI:'NFC East',PIT:'AFC North',SEA:'NFC West',SF:'NFC West',TB:'NFC South',TEN:'AFC South',WAS:'NFC East'};
function score(id){return (live.scores||[]).find(x=>x.game_id===id)}
function meta(id){return live.game_meta?.[id]||{}}
function kickoff(g){return score(g.game_id)?.commence_utc||meta(g.game_id).commence_utc||KICKOFF[g.game_id]||null}
function kickoffText(g){const s=score(g.game_id);if(s?.state==='FINAL')return 'FINAL';if(s?.state==='LIVE')return s.detail||'LIVE';const k=kickoff(g);return k?new Date(k).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}):'SCHEDULED'}
function statusBadge(g){const s=score(g.game_id);if(s?.state==='FINAL')return '<span class="badge lock">FINAL</span>';if(s?.state==='LIVE')return '<span class="badge live">LIVE</span>';if(g.locked)return '<span class="badge lock">LOCKED</span>';if(g.status==='AUDIT_ONLY_POST_KICKOFF')return '<span class="badge">AUDIT</span>';return '<span class="badge">CURRENT</span>'}
function hist(g){return marketHistory[g.game_id]||[]}
function currentMarket(g){const h=hist(g);return h.length?h[h.length-1].display:(g.market||'—')}
function currentBooks(g){const h=hist(g);return h.length?h[h.length-1].books:null}
function visible(){let a=[...(model.games||[])];if(filter==='locked')a=a.filter(g=>g.locked);if(filter==='signal')a=a.filter(g=>g.signal_4plus);const q=($('#globalSearch')?.value||'').trim().toUpperCase();if(q)a=a.filter(g=>`${g.away} ${g.home} ${g.game_id}`.includes(q));return a}
function resultMargin(s){return s?Number(s.home_score)-Number(s.away_score):null}
function marginError(g){const s=score(g.game_id);if(!s||s.state!=='FINAL'||g.our_line_internal==null)return null;return Math.abs(resultMargin(s)-Number(g.our_line_internal))}
function terminalRow(g){const hot=(g.edge||0)>=4;return `<div class="terminal-row ${selectedGame===g.game_id?'selected':''}" data-game="${g.game_id}"><div class="game-name">${g.away} @ ${g.home}<small>${kickoffText(g)} · ${statusBadge(g)}</small></div><div class="metric"><span>Our line</span><b>${g.our_line||'—'}</b></div><div class="metric"><span>Market</span><b>${currentMarket(g)}</b></div><div class="metric"><span>Edge</span><b class="${hot?'hot':''}">${fmt(g.edge)}</b></div></div>`}
function softwareCard(g){const hot=(g.edge||0)>=4,s=score(g.game_id);return `<article class="software-card" data-game="${g.game_id}"><div class="software-card-top"><span>${kickoffText(g)}</span>${statusBadge(g)}</div><h3>${g.away} @ ${g.home}</h3>${s?.state==='FINAL'?`<div class="muted">${s.away} ${s.away_score} · ${s.home} ${s.home_score}</div>`:''}<div class="software-card-metrics"><div><span>Our</span><b>${g.our_line||'—'}</b></div><div><span>Market</span><b>${currentMarket(g)}</b></div><div><span>Edge</span><b class="${hot?'hot':''}">${fmt(g.edge)}</b></div></div></article>`}
function bindGameClicks(){$$('[data-game]').forEach(el=>el.onclick=()=>selectGame(el.dataset.game))}
function renderStatStrip(){const gs=model.games||[],locked=gs.filter(g=>g.locked).length,finals=gs.filter(g=>score(g.game_id)?.state==='FINAL').length,signals=gs.filter(g=>g.signal_4plus).length,inj=(live.injuries||[]).filter(x=>x.game_status==='Out').length;$('#statStrip').innerHTML=[[gs.length,'Week games'],[locked,'Immutable live'],[signals,'4+ discrepancies'],[inj,'Players out'],[finals,'Final games']].map(([v,l])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('')}
function renderCommand(){$('#terminalGameList').innerHTML=visible().map(terminalRow).join('');const outs=(live.injuries||[]).filter(x=>x.game_status==='Out').sort((a,b)=>(b.usage_60d||0)-(a.usage_60d||0)).slice(0,5);$('#quickInjuries').innerHTML=outs.length?outs.map(x=>`<div class="quick-row"><span>${x.team} · ${x.player}</span><b class="out">OUT</b></div>`).join(''):'<div class="quick-row"><span>No OUT rows</span><b>—</b></div>';const biggest=[...(model.games||[])].filter(g=>g.edge!=null).sort((a,b)=>b.edge-a.edge)[0];$('#topEdge').innerHTML=biggest?`<div class="quick-row"><span>${biggest.away} @ ${biggest.home}</span><b class="hot">${fmt(biggest.edge)} pts</b></div><div class="quick-row"><span>Model side</span><b>${biggest.model_side||'—'}</b></div><div class="quick-row"><span>State</span><b>${biggest.locked?'LOCKED':'CURRENT'}</b></div>`:'<div class="quick-row"><span>No market edge</span><b>—</b></div>';$('#systemHealth').innerHTML=[['Fair-line engine','FROZEN'],['Market isolation','PASS'],['Injury bridge','ONLINE'],['Live ledger','APPEND-ONLY'],['Data refresh','ONLINE']].map(([a,b])=>`<div class="system-row"><span>${a}</span><b class="healthy">${b}</b></div>`).join('');bindGameClicks()}
function featureMarkup(g){const f=features[g.game_id];if(!f)return `<div class="section-block"><h3>Feature vector</h3><p class="muted">Detailed frozen feature vector has not yet been published for this game. The public terminal will fill this as each game reaches final lock.</p></div>`;const groups={};f.features.forEach(x=>{(groups[x.group]??=[]).push(x)});return Object.entries(groups).map(([group,rows])=>`<div class="feature-group">${group}</div><table class="feature-table">${rows.map(x=>`<tr><td>${x.label}</td><td>${fmt(x.value,6)}</td></tr>`).join('')}</table>`).join('')}
function overviewMarkup(g){const s=score(g.game_id),m=meta(g.game_id),inj=(live.injuries||[]).filter(x=>x.team===g.away||x.team===g.home);return `<div class="section-block"><h3>Game state</h3><div class="info-grid"><div class="info-card"><span>Kickoff</span><b>${kickoff(g)?new Date(kickoff(g)).toLocaleString():'—'}</b></div><div class="info-card"><span>Venue</span><b>${m.venue||'—'}</b></div><div class="info-card"><span>Network</span><b>${m.network||'—'}</b></div><div class="info-card"><span>Record state</span><b>${g.locked?'IMMUTABLE':'NOT YET LOCKED'}</b></div></div></div>${s?`<div class="section-block"><h3>Score</h3><div class="info-card"><span>${s.state}</span><b>${s.away} ${s.away_score} · ${s.home} ${s.home_score}</b></div></div>`:''}<div class="section-block"><h3>Injury watch</h3>${inj.length?inj.map(x=>`<div class="quick-row"><span>${x.team} · ${x.player} · ${x.position||''}</span><b class="${x.game_status==='Out'?'out':'signal'}">${x.game_status}</b></div>`).join(''):'<p class="muted">No frozen-status injury rows currently displayed.</p>'}</div>`}
function marketMarkup(g){const h=hist(g);return `<div class="section-block"><h3>Captured market history</h3>${h.length?h.map(x=>`<div class="quick-row"><span>${new Date(x.ts).toLocaleString()}</span><b>${x.display} · ${x.books??'—'} books</b></div>`).join(''):'<p class="muted">No market history snapshots published yet.</p>'}</div><div class="section-block"><h3>Research status</h3><div class="info-grid"><div class="info-card"><span>Difference</span><b>${fmt(g.edge)} pts</b></div><div class="info-card"><span>Model side</span><b>${g.model_side||'—'}</b></div><div class="info-card"><span>4+ signal</span><b>${g.signal_4plus?'YES':'NO'}</b></div><div class="info-card"><span>Certified betting rule</span><b>NO</b></div></div></div>`}
function renderInspectorTab(g,tab){const c=$('#inspectorContent');if(tab==='features')c.innerHTML=featureMarkup(g);else if(tab==='market')c.innerHTML=marketMarkup(g);else c.innerHTML=overviewMarkup(g);$$('.inspector-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.itab===tab))}
function selectGame(id){selectedGame=id;const g=(model.games||[]).find(x=>x.game_id===id);if(!g)return;$('#inspectorEmpty').classList.add('hidden');$('#gameInspector').classList.remove('hidden');const hot=(g.edge||0)>=4;$('#gameInspector').innerHTML=`<div class="inspector-hero"><div class="inspector-kicker"><span>${kickoffText(g)}</span>${statusBadge(g)}</div><div class="inspector-matchup"><div class="team-chip"><span class="team-logo">${g.away}</span>${g.away}</div><span class="at">@</span><div class="team-chip"><span class="team-logo">${g.home}</span>${g.home}</div></div><div class="model-banner"><div class="model-box"><span>Our line</span><b>${g.our_line||'—'}</b></div><div class="model-box"><span>Market</span><b>${currentMarket(g)}</b></div><div class="model-box"><span>Difference</span><b class="${hot?'hot':''}">${fmt(g.edge)}</b></div><div class="model-box"><span>Model side</span><b>${g.model_side||'—'}</b></div></div></div><div class="inspector-tabs"><button class="active" data-itab="overview">Overview</button><button data-itab="features">Features</button><button data-itab="market">Market</button></div><div id="inspectorContent" class="inspector-content"></div>`;renderInspectorTab(g,'overview');$$('.inspector-tabs button').forEach(b=>b.onclick=()=>renderInspectorTab(g,b.dataset.itab));renderCommand()}
function renderGames(){const gs=visible();$('#gamesMatrix').innerHTML=gs.map(softwareCard).join('');bindGameClicks()}
function renderMarket(){const gs=[...(model.games||[])].filter(g=>g.market||hist(g).length),avg=gs.length?gs.reduce((s,g)=>s+(g.edge||0),0)/gs.length:0,four=gs.filter(g=>(g.edge||0)>=4).length,books=gs.map(currentBooks).filter(x=>x!=null);$('#marketStats').innerHTML=[[gs.length,'Games captured'],[fmt(avg),'Avg difference'],[four,'4+ gaps'],[books.length?fmt(books.reduce((a,b)=>a+b,0)/books.length,1):'—','Avg books']].map(([v,l])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('');$('#marketRows').innerHTML=gs.sort((a,b)=>(b.edge||0)-(a.edge||0)).map(g=>`<tr><td><b>${g.away} @ ${g.home}</b></td><td>${g.our_line||'—'}</td><td>${currentMarket(g)}</td><td class="${(g.edge||0)>=4?'hot':''}">${fmt(g.edge)} pts</td><td><b>${g.model_side||'—'}</b></td><td>${currentBooks(g)??'—'}</td><td>${g.locked?'<span class="badge lock">LOCKED</span>':g.signal_4plus?'<span class="badge signal">4+ CURRENT</span>':'<span class="badge">CURRENT</span>'}</td></tr>`).join('')}
function renderInjuries(){const arr=[...(live.injuries||[])].sort((a,b)=>a.team.localeCompare(b.team)||a.player.localeCompare(b.player)),outs=arr.filter(x=>x.game_status==='Out'),qs=arr.filter(x=>x.game_status==='Questionable'),burden=outs.reduce((s,x)=>s+(x.usage_60d||0),0);$('#injurySummary').innerHTML=[[arr.length,'Rows displayed'],[outs.length,'Out'],[qs.length,'Questionable'],[fmt(burden*100,1)+'%','Combined prior usage OUT']].map(([v,l])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('');$('#injuryRows').innerHTML=arr.map(x=>`<tr><td><b>${x.team}</b></td><td>${x.player}</td><td>${x.position||'—'}</td><td>${x.injury||'—'}</td><td>${x.practice||'—'}</td><td><span class="badge ${x.game_status==='Out'?'out':'q'}">${x.game_status||'—'}</span></td><td>${fmt((x.usage_60d||0)*100,1)}%</td></tr>`).join('')}
function renderPerformance(){const gs=model.games||[],locked=gs.filter(g=>g.locked),completed=locked.filter(g=>score(g.game_id)?.state==='FINAL'),errs=completed.map(marginError).filter(x=>x!=null),mae=errs.length?errs.reduce((a,b)=>a+b,0)/errs.length:null;$('#performanceStats').innerHTML=[[locked.length,'Immutable live'],[completed.length,'Scored live'],[mae==null?'PENDING':fmt(mae),'Live MAE'],[locked.filter(g=>g.signal_4plus).length,'Locked 4+']].map(([v,l])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('');$('#performanceRows').innerHTML=gs.map(g=>{const s=score(g.game_id),e=marginError(g);return `<tr><td><b>${g.away} @ ${g.home}</b></td><td>${g.our_line||'—'}</td><td>${g.market||'—'}</td><td>${fmt(g.edge)}</td><td>${g.model_side||'—'}</td><td>${s?.state==='FINAL'?`${s.away} ${s.away_score} · ${s.home} ${s.home_score}`:'—'}</td><td>${e==null?'—':fmt(e)}</td><td>${g.locked?'<span class="badge lock">IMMUTABLE</span>':g.status==='AUDIT_ONLY_POST_KICKOFF'?'<span class="badge">AUDIT</span>':'<span class="badge">PENDING LOCK</span>'}</td></tr>`}).join('')}
function renderStandings(){const rec=live.records||{},all=[...new Set((model.games||[]).flatMap(g=>[g.away,g.home]))],divs={};all.forEach(t=>{const d=teams[t]?.division||DIVS[t]||'NFL';(divs[d]??=[]).push(t)});$('#standingsGrid').innerHTML=Object.keys(divs).sort().map(d=>`<article class="division-card"><h3>${d}</h3>${divs[d].sort().map(t=>`<div class="division-row"><span><b>${t}</b> <span class="muted">${teams[t]?.name||''}</span></span><b>${rec[t]||'0-0'}</b></div>`).join('')}</article>`).join('')}
function switchView(view){$$('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));const titles={command:['WORKSPACE','Command Center'],games:['SCHEDULE','Games'],market:['LINES','Market Monitor'],injuries:['PLAYER STATUS','Injury Center'],performance:['LIVE LEDGER','Performance'],standings:['2026 SEASON','Standings'],model:['ARCHITECTURE','Model Console']};$('#viewEyebrow').textContent=titles[view][0];$('#viewTitle').textContent=titles[view][1];if(view==='games')renderGames();if(view==='market')renderMarket();if(view==='injuries')renderInjuries();if(view==='performance')renderPerformance();if(view==='standings')renderStandings()}
function renderAll(){const dt=live.updated_at_utc||model.generated_at_utc;$('#updated').textContent=dt?new Date(dt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Offline';renderStatStrip();renderCommand();renderGames();renderMarket();renderInjuries();renderPerformance();renderStandings();if(!selectedGame){const first=(model.games||[]).find(g=>g.locked)||(model.games||[])[0];if(first)selectGame(first.game_id)}}
$$('.side-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderCommand();renderGames()});$('#globalSearch').addEventListener('input',()=>{renderCommand();renderGames()});document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('#globalSearch')){e.preventDefault();$('#globalSearch').focus()}if(e.key==='1')switchView('command');if(e.key==='2')switchView('games');if(e.key==='3')switchView('market');if(e.key==='4')switchView('injuries')});
const get=(p,fallback={})=>fetch(`${p}?${Date.now()}`).then(r=>r.ok?r.json():fallback).catch(()=>fallback);
Promise.all([get('data/model_snapshot.json',{games:[]}),get('data/dashboard.json',{}),get('data/teams.json',{}),get('data/market_history.json',{}),get('data/game_features.json',{})]).then(([m,l,t,h,f])=>{model=m;live=l;teams=t;marketHistory=h;features=f;renderAll()}).catch(err=>{$('#updated').textContent='Data error';console.error(err)});
