(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VIEWS=['command','games','market','injuries','news','performance','standings','model'];
function activeView(){return $('.side-nav button.active')?.dataset.view||'command'}
function switchView(id){const b=$(`.side-nav button[data-view="${id}"]`);if(b)b.click()}
function ribbon(){ $$('.view-head').forEach(h=>{if(h.querySelector('.v82-ribbon'))return;const r=document.createElement('div');r.className='v82-ribbon';r.innerHTML='<span class="v82-tag good">Verified layers only</span><span class="v82-tag blue">Model isolated</span><span class="v82-tag">Keyboard 1–8</span>';const left=h.firstElementChild;left?.appendChild(r)}) }
function lowerDeck(id,html){const v=$(`#view-${id}`);if(!v||v.querySelector('.v82-lowerdeck'))return;const d=document.createElement('div');d.className='v82-lowerdeck';d.innerHTML=html;v.appendChild(d)}
function buildDecks(){
 lowerDeck('market','<section class="v82-module"><h3>Market protocol</h3><p><b>Consensus is benchmark only.</b> The EDGEiQ fair line is built first and remains isolated from market input.</p></section><section class="v82-module"><h3>Decision standard</h3><p>Best actionable price is displayed separately from the research benchmark. No line-shopping result is allowed to rewrite the model.</p></section><section class="v82-module"><h3>Signal governance</h3><p>The historical 4+ point discrepancy band remains <b>post-hoc / uncertified</b> until prospectively validated.</p></section>');
 lowerDeck('injuries','<section class="v82-module"><h3>Availability policy</h3><p>Only published player status and verified prior-usage context belong in this layer. Missing players are never inferred.</p></section><section class="v82-module"><h3>Model boundary</h3><p>Personnel information shown in the terminal does not automatically become a model feature. The frozen production architecture remains protected.</p></section><section class="v82-module"><h3>Status legend</h3><div class="v82-minirow"><span>OUT</span><strong style="color:#ff6070">Unavailable</strong></div><div class="v82-minirow"><span>QUESTIONABLE</span><strong style="color:#ffd15a">Monitor</strong></div><div class="v82-minirow"><span>ACTIVE</span><strong style="color:#47df9b">Available</strong></div></section>');
 lowerDeck('performance','<section class="v82-module"><h3>Prospective ledger</h3><p>Experiment 030 is append-only. A locked pregame fair line is never changed after kickoff or result.</p></section><section class="v82-module"><h3>Scoring</h3><p>Completed games will populate error and performance fields from the immutable record rather than retrospective reconstruction.</p></section><section class="v82-module"><h3>Research rule</h3><p><b>No post-result rewrites.</b> Challenger architectures require separate preregistered research before replacing the control.</p></section>');
 lowerDeck('standings','<section class="v82-module"><h3>League context</h3><p>Standings are an information layer for schedule and situational context. They do not alter the frozen fair line by themselves.</p></section><section class="v82-module"><h3>Season state</h3><p>2026 records update as official results arrive, with team aliases normalized across historical franchise codes.</p></section><section class="v82-module"><h3>Game access</h3><p>Use the Week 1 ticker or Games board to jump directly from league context into the full Game Control Centre.</p></section>');
 lowerDeck('model','<section class="v82-module"><h3>Production architecture</h3><div class="v82-minirow"><span>Engine</span><strong>008A RIDGE</strong></div><div class="v82-minirow"><span>Football core</span><strong>002D SUCCESS</strong></div><div class="v82-minirow"><span>Personnel layer</span><strong>007C STATUS</strong></div></section><section class="v82-module"><h3>Information firewall</h3><div class="v82-minirow"><span>Market input</span><strong style="color:#47df9b">NO</strong></div><div class="v82-minirow"><span>News input</span><strong style="color:#47df9b">NO</strong></div><div class="v82-minirow"><span>Live PBP input</span><strong style="color:#47df9b">NO</strong></div></section><section class="v82-module"><h3>Walk-forward discipline</h3><p>Pregame information only. Target-game performance is excluded, model numbers are created before market comparison, and live production rows remain immutable.</p></section>');
}
function sortTable(th){const table=th.closest('table'),body=table?.tBodies?.[0];if(!body)return;const idx=[...th.parentNode.children].indexOf(th);const asc=th.dataset.dir!=='asc';$$('th',table).forEach?.(()=>{});table.querySelectorAll('th').forEach(x=>{x.classList.remove('v82-sort');delete x.dataset.dir});th.classList.add('v82-sort');th.dataset.dir=asc?'asc':'desc';const rows=[...body.rows];rows.sort((a,b)=>{const A=a.cells[idx]?.innerText.trim()||'',B=b.cells[idx]?.innerText.trim()||'';const na=parseFloat(A.replace(/[^0-9.-]/g,'')),nb=parseFloat(B.replace(/[^0-9.-]/g,''));const cmp=Number.isFinite(na)&&Number.isFinite(nb)?na-nb:A.localeCompare(B,undefined,{numeric:true});return asc?cmp:-cmp});rows.forEach(r=>body.appendChild(r))}
function search(q){q=q.trim().toLowerCase();$$('.terminal-row,.software-card,.news-card,.v8-tick').forEach(el=>{const show=!q||el.innerText.toLowerCase().includes(q);el.style.display=show?'':'none'})}
function enhanceGcc(){const host=$('#edgeiqV7');if(!host)return;const bar=host.querySelector('.v7-bar');if(!bar||bar.querySelector('.v82-gcc-nav'))return;const old=bar.querySelector('.v7-back');if(old)old.style.display='none';const nav=document.createElement('div');nav.className='v82-gcc-nav';nav.innerHTML='<button class="v82-gcc-btn" data-gcc-prev>← PREV</button><button class="v82-gcc-btn" data-gcc-board>GAME BOARD</button><button class="v82-gcc-btn" data-gcc-next>NEXT →</button>';bar.appendChild(nav)}
function cycleGame(step){const id=new URLSearchParams(location.search).get('game');const games=window.NFLModel?.games||[];if(!games.length)return;let i=games.findIndex(g=>g.game_id===id);if(i<0)i=0;i=(i+step+games.length)%games.length;window.EDGEiQGameCentre?.open?.(games[i].game_id)}
function wire(){document.addEventListener('keydown',e=>{if(/^[1-8]$/.test(e.key)&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){switchView(VIEWS[Number(e.key)-1]);e.preventDefault()}if(e.altKey&&e.key==='ArrowLeft')cycleGame(-1);if(e.altKey&&e.key==='ArrowRight')cycleGame(1)});document.addEventListener('click',e=>{const th=e.target.closest('th');if(th)sortTable(th);if(e.target.closest('[data-gcc-prev]'))cycleGame(-1);if(e.target.closest('[data-gcc-next]'))cycleGame(1);if(e.target.closest('[data-gcc-board]'))window.EDGEiQGameCentre?.close?.()});const input=$('#globalSearch');if(input)input.addEventListener('input',()=>search(input.value))}
function boot(){document.documentElement.dataset.edgeiqUi='v82';const ver=$('.version');if(ver)ver.textContent='v8.2 · operator workspace';ribbon();buildDecks();wire();enhanceGcc();const obs=new MutationObserver(()=>{ribbon();buildDecks();enhanceGcc()});obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();