(()=>{
'use strict';
const INTERVAL_MS=30000,STALE_MS=7*60*1000;
let busy=false,lastOk=0;
const stamp=()=>new Date().toISOString();
async function get(path){const r=await fetch(`${path}?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
function ageMs(d){const t=Date.parse(d||'');return Number.isFinite(t)?Math.max(0,Date.now()-t):Infinity}
function freshness(d){const ms=ageMs(d);if(!Number.isFinite(ms))return{state:'UNKNOWN',label:'FEED AGE UNKNOWN',ms};if(ms>STALE_MS)return{state:'STALE',label:`FEED STALE · ${Math.floor(ms/60000)}M`,ms};return{state:'FRESH',label:`FEED ${Math.max(0,Math.floor(ms/60000))}M`,ms}}
function feedState(data){const f=freshness(data?.updated_at_utc),health=data?.feed_health||{},source=health.source||data?.score_source||'UNKNOWN';if(health.scoreboard_ok===false&&f.state==='FRESH')return{...f,state:'DEGRADED',label:'FEED DEGRADED',source};return{...f,source}}
function publishGlobals(){try{if(typeof live!=='undefined')window.NFLLive=live}catch(_){}try{if(typeof marketHistory!=='undefined')window.NFLMarketHistory=marketHistory}catch(_){}try{if(typeof news!=='undefined')window.NFLNews=news}catch(_){}}
function callRenders(){publishGlobals();try{if(typeof renderStatStrip==='function')renderStatStrip()}catch(_){}try{if(typeof renderCommand==='function')renderCommand()}catch(_){}try{if(typeof renderGames==='function')renderGames()}catch(_){}try{if(typeof renderMarket==='function')renderMarket()}catch(_){}try{if(typeof renderInjuries==='function')renderInjuries()}catch(_){}try{if(typeof renderNews==='function')renderNews()}catch(_){}try{if(typeof renderPerformance==='function')renderPerformance()}catch(_){}try{if(typeof renderStandings==='function')renderStandings()}catch(_){}try{if(typeof selectedGame!=='undefined'&&selectedGame&&typeof selectGame==='function')selectGame(selectedGame)}catch(_){}const f=feedState((typeof live!=='undefined'&&live)||window.NFLLive||{});document.dispatchEvent(new CustomEvent('nflops:information-refresh',{detail:{ts:stamp(),freshness:f}}));document.dispatchEvent(new CustomEvent('nflops:context',{detail:{source:f.source,freshness:f}}))}
function setState(ok,msg){const data=(typeof live!=='undefined'&&live)||window.NFLLive||{},f=feedState(data),el=document.getElementById('liveOpsState'),good=ok&&f.state==='FRESH',bad=ok&&(f.state==='STALE'||f.state==='DEGRADED');if(el){el.textContent=!ok?'REFRESH ERR':f.state==='FRESH'?`${f.source} · ${f.label}`:f.label;el.classList.toggle('healthy',good);el.classList.toggle('stale',bad);el.title=msg||''}const u=document.getElementById('updated');if(u&&ok){u.textContent=f.state==='FRESH'?`${f.source} · ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:f.label;u.title=`Published ${data.updated_at_utc||'unknown'} · checked ${data.checked_at_utc||'unknown'} · source ${f.source} · frozen 008A unchanged`}document.body.dataset.feedFreshness=f.state.toLowerCase();document.body.dataset.feedSource=f.source.toLowerCase()}
async function refresh(){if(busy)return;busy=true;try{const [dash,mkt,intel,personnel]=await Promise.allSettled([get('data/dashboard.json'),get('data/market_history.json'),get('data/news.json'),get('data/personnel.json')]);if(dash.status==='fulfilled'){if(typeof live!=='undefined')live=dash.value;window.NFLLive=dash.value}if(mkt.status==='fulfilled'){if(typeof marketHistory!=='undefined')marketHistory=mkt.value;window.NFLMarketHistory=mkt.value}if(intel.status==='fulfilled'){if(typeof news!=='undefined')news=intel.value;window.NFLNews=intel.value}if(personnel.status==='fulfilled')window.NFLPersonnel=personnel.value;lastOk=Date.now();callRenders();const f=feedState(window.NFLLive||{});setState(true,`Browser checked ${stamp()}. Backend checks every 5 minutes. Published source: ${f.source}. State: ${f.state}. Frozen model is unchanged.`)}catch(e){setState(false,String(e))}finally{busy=false}}
function install(){publishGlobals();const host=document.querySelector('.command-actions');if(host&&!document.getElementById('liveOpsState')){const b=document.createElement('div');b.id='liveOpsState';b.className='live-ops-state';b.textContent='SYNCING FEED';host.insertBefore(b,host.querySelector('.sync'))}refresh();setInterval(refresh,INTERVAL_MS);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-lastOk>INTERVAL_MS)refresh()})}
window.EDGEiQFeed={freshness:()=>feedState(window.NFLLive||{}),refresh};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();