(()=>{
'use strict';
const INTERVAL_MS=30000;
let busy=false,lastOk=0;
const stamp=()=>new Date().toISOString();
async function get(path){const r=await fetch(`${path}?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
function callRenders(){try{if(typeof renderStatStrip==='function')renderStatStrip()}catch(_){}try{if(typeof renderCommand==='function')renderCommand()}catch(_){}try{if(typeof renderGames==='function')renderGames()}catch(_){}try{if(typeof renderMarket==='function')renderMarket()}catch(_){}try{if(typeof renderInjuries==='function')renderInjuries()}catch(_){}try{if(typeof renderNews==='function')renderNews()}catch(_){}try{if(typeof renderPerformance==='function')renderPerformance()}catch(_){}try{if(typeof renderStandings==='function')renderStandings()}catch(_){}try{if(typeof selectedGame!=='undefined'&&selectedGame&&typeof selectGame==='function')selectGame(selectedGame)}catch(_){}document.dispatchEvent(new CustomEvent('nflops:information-refresh',{detail:{ts:stamp()}}));document.dispatchEvent(new CustomEvent('nflops:context',{detail:{source:'live-ops'}}))}
function setState(ok,msg){const el=document.getElementById('liveOpsState');if(el){el.textContent=ok?'UI 30S · FEED 5M':'REFRESH ERR';el.classList.toggle('healthy',ok);el.title=msg||''}const u=document.getElementById('updated');if(u&&ok){const src=(typeof live!=='undefined'&&live?.score_source)?' · SCORE FEED':'';u.textContent='LIVE '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+src}}
async function refresh(){if(busy)return;busy=true;try{const [dash,mkt,intel,personnel]=await Promise.allSettled([get('data/dashboard.json'),get('data/market_history.json'),get('data/news.json'),get('data/personnel.json')]);if(dash.status==='fulfilled'&&typeof live!=='undefined')live=dash.value;if(mkt.status==='fulfilled'&&typeof marketHistory!=='undefined')marketHistory=mkt.value;if(intel.status==='fulfilled'&&typeof news!=='undefined')news=intel.value;if(personnel.status==='fulfilled')window.NFLPersonnel=personnel.value;lastOk=Date.now();callRenders();setState(true,`Published information checked ${stamp()}. Live scoreboard backend scheduled every 5 minutes; browser checks published state every 30 seconds. Model is unchanged.`)}catch(e){setState(false,String(e))}finally{busy=false}}
function install(){const host=document.querySelector('.command-actions');if(host&&!document.getElementById('liveOpsState')){const b=document.createElement('div');b.id='liveOpsState';b.className='live-ops-state healthy';b.textContent='UI 30S · FEED 5M';b.title='Browser checks published information every 30 seconds. Live scoreboard backend refresh is scheduled every 5 minutes. Model is not refit or mutated.';host.insertBefore(b,host.querySelector('.sync'))}refresh();setInterval(refresh,INTERVAL_MS);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-lastOk>INTERVAL_MS)refresh()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();