(()=>{
'use strict';
const ROUTES={F1:'command',F2:'games',F3:'market',F4:'injuries',F5:'news',F6:'performance',F7:'standings',F8:'model'};
const COMMANDS=[['COMMAND','command','Open command workspace'],['GAMES','games','Open Week 1 game board'],['MARKET','market','Open market monitor'],['INJURIES','injuries','Open official injury center'],['INTEL','news','Open intelligence desk'],['PERFORMANCE','performance','Open prospective model ledger'],['STANDINGS','standings','Open NFL standings'],['MODEL','model','Open frozen model console']];
function nav(view){const b=document.querySelector(`.side-nav [data-view="${view}"]`);if(b)b.click()}
function gameRows(){return [...document.querySelectorAll('#terminalGameList [data-game]')].filter(x=>x.offsetParent!==null)}
function moveGame(step){const rows=gameRows();if(!rows.length)return;let i=rows.findIndex(x=>x.classList.contains('selected'));i=i<0?(step>0?-1:0):i;rows[(i+step+rows.length)%rows.length].click()}
function palette(){let p=document.getElementById('operatorPalette');if(p)return p;document.body.insertAdjacentHTML('beforeend',`<div id="operatorPalette" class="op-palette hidden"><div class="op-palette-box"><div class="op-palette-head"><span>GO / COMMAND</span><kbd>ESC</kbd></div><input id="operatorCommand" autocomplete="off" placeholder="TYPE COMMAND, VIEW OR TEAM…"><div id="operatorResults" class="op-results"></div><div class="op-palette-foot">ENTER OPEN · ↑↓ MOVE · F1–F8 WORKSPACES</div></div></div>`);p=document.getElementById('operatorPalette');const input=document.getElementById('operatorCommand');input.addEventListener('input',renderResults);input.addEventListener('keydown',e=>{if(e.key==='Escape'){closePalette();return}const rows=[...document.querySelectorAll('.op-result')];let i=rows.findIndex(x=>x.classList.contains('active'));if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();rows.forEach(x=>x.classList.remove('active'));i=e.key==='ArrowDown'?Math.min(rows.length-1,i+1):Math.max(0,i<0?0:i-1);rows[i]?.classList.add('active');rows[i]?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'){e.preventDefault();(rows.find(x=>x.classList.contains('active'))||rows[0])?.click()}});return p}
function renderResults(){const q=(document.getElementById('operatorCommand')?.value||'').trim().toUpperCase();const base=COMMANDS.filter(x=>!q||`${x[0]} ${x[2]}`.includes(q));const games=[...document.querySelectorAll('#terminalGameList [data-game]')].map(x=>[x.dataset.game,x.querySelector('.game-name')?.childNodes[0]?.textContent?.trim()||x.dataset.game]).filter(x=>!q||`${x[0]} ${x[1]}`.toUpperCase().includes(q));const out=[...base.map(x=>({label:x[0],sub:x[2],go:()=>nav(x[1])})),...games.slice(0,8).map(x=>({label:x[1],sub:`GAME · ${x[0]}`,go:()=>document.querySelector(`#terminalGameList [data-game="${x[0]}"]`)?.click()}))];document.getElementById('operatorResults').innerHTML=out.map((x,i)=>`<button class="op-result ${i===0?'active':''}" data-i="${i}"><b>${x.label}</b><span>${x.sub}</span></button>`).join('')||'<div class="op-none">NO MATCH</div>';[...document.querySelectorAll('.op-result')].forEach((el,i)=>el.onclick=()=>{out[i].go();closePalette()})}
function openPalette(seed=''){const p=palette();p.classList.remove('hidden');const i=document.getElementById('operatorCommand');i.value=seed;renderResults();setTimeout(()=>i.focus(),0)}function closePalette(){document.getElementById('operatorPalette')?.classList.add('hidden')}
function hotkeyMap(){let x=document.getElementById('hotkeyMap');if(x){x.remove();return}document.body.insertAdjacentHTML('beforeend',`<div id="hotkeyMap" class="hotkey-map"><div><b>OPERATOR KEYS</b><span>F1 Command</span><span>F2 Games</span><span>F3 Market</span><span>F4 Injuries</span><span>F5 Intelligence</span><span>F6 Performance</span><span>F7 Standings</span><span>F8 Model</span><span>Ctrl+K / Ctrl+G Command bar</span><span>/ Search</span><span>J / K Next / previous game</span><span>? Toggle this map</span></div></div>`)}
function addStatus(){if(document.getElementById('operatorStatus'))return;document.body.insertAdjacentHTML('beforeend',`<footer id="operatorStatus" class="operator-status"><span><i></i> LIVE TERMINAL</span><span>008A RIDGE · FROZEN</span><span>MARKET INPUT: NO</span><span>INTEL INPUT: NO</span><span class="op-spacer"></span><span>F1–F8 WORKSPACES</span><span>CTRL+K GO</span><span>J/K GAME</span><span>? KEYS</span></footer>`)}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&(e.key.toLowerCase()==='k'||e.key.toLowerCase()==='g')){e.preventDefault();openPalette();return}if(e.key in ROUTES){e.preventDefault();nav(ROUTES[e.key]);return}if(e.key==='?'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){hotkeyMap();return}if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){e.preventDefault();document.getElementById('globalSearch')?.focus();return}if(!/INPUT|TEXTAREA/.test(document.activeElement?.tagName)){if(e.key.toLowerCase()==='j')moveGame(1);if(e.key.toLowerCase()==='k')moveGame(-1)}});
document.addEventListener('DOMContentLoaded',()=>{palette();addStatus();document.querySelector('.command-bar')?.insertAdjacentHTML('beforeend','<button class="op-go" id="opGo">GO <kbd>Ctrl K</kbd></button>');document.getElementById('opGo')?.addEventListener('click',()=>openPalette());});
})();